### ISSUE TITLE
Error on send snapshot

### ISSUE THREAD

**Issue by irossett** [tasket/wyng-backup#129]
Good morning,
sometimes, when I use "wyng send", it exits with status code. For example

```
root@dardo:~/wyng-backup-master# wyng send vm-103-disk-0
Wyng 0.3.2 release 20220818
Preparing snapshots...
Traceback (most recent call last):
  File "/usr/local/bin/wyng", line 2977, in <module>
    monitor_send(datavols, selected_vols, monitor_only=False)
  File "/usr/local/bin/wyng", line 1761, in monitor_send
    = prepare_snapshots(selected if len(selected) >0 else datavols)
  File "/usr/local/bin/wyng", line 1284, in prepare_snapshots
    + ["--addtag=arch-"+aset.uuid, "-s", vgname+"/"+datavol, "-n",snap2vol]])
  File "/usr/local/bin/wyng", line 1154, in do_exec
    raise subprocess.CalledProcessError(err.returncode, err.args)
subprocess.CalledProcessError: Command '['/sbin/lvm', 'lvcreate', '-pr', '-kn', '-ay', '--addtag=wyng', '--addtag=arch-90a1ad0a-bd01-4036-9c62-a551b3733626', '-s', 'pve/vm-103-disk-0', '-n', 'vm-103-disk-0.tock']' returned non-zero exit status 5.                         
```

after a second try:

```
root@dardo:~/wyng-backup-master# wyng send vm-103-disk-0
Wyng 0.3.2 release 20220818
Preparing snapshots...


Sending backup session 20221214-091510 to ssh://root@backup
  100%     946.7M  |  vm-103-disk-0 Traceback (most recent call last):
  File "/usr/local/bin/wyng", line 2977, in <module>
    monitor_send(datavols, selected_vols, monitor_only=False)
  File "/usr/local/bin/wyng", line 1822, in monitor_send
    dnew, dfreed = send_volume(datavol, localtime, ses_tags, send_all=datavol in send_alls)
  File "/usr/local/bin/wyng", line 1652, in send_volume
    rotate_snapshots(vol, rotate=True)
  File "/usr/local/bin/wyng", line 1846, in rotate_snapshots
    lv_remove(aset.vgname, snap1vol)    ; lv_rename(aset.vgname, snap2vol, snap1vol)
  File "/usr/local/bin/wyng", line 521, in lv_rename
    do_exec([[CP.lvm, "lvrename", vgname+"/"+vol1, vol2]])    ; lvs = volgroups[vgname].lvs
  File "/usr/local/bin/wyng", line 1154, in do_exec
    raise subprocess.CalledProcessError(err.returncode, err.args)
subprocess.CalledProcessError: Command '['/sbin/lvm', 'lvrename', 'pve/vm-103-disk-0.tock', 'vm-103-disk-0.tick']' returned non-zero exit status 5.
```

but if I check the status it seems OK ( //20221214-091510//)

```
root@dardo:~/wyng-backup-master# wyng list vm-103-disk-0
Wyng 0.3.2 release 20220818

Sessions for volume 'vm-103-disk-0':

20221213-021629  20221214-091510
```

I don't understand this happen, sometimes it ok, sometimes I get errors. I have no problem to retry, but what I need to understand is:
 "After a fault, what is the snapshot status? May I trust or I have to delete all the snapshots and restart from the beginning?"

Thank for you work!

**Comment by tasket** [comment]
@irossett Being an intermittent error, could it be a reliability problem with the volume group or pv?  Note that the `lvcreate` or `lvrename` actions are often (or always, in the latter case) executing immediately after a deletion of the new volume name, for example:

```
lvremove vg/vol1
lvrename vg/vol2 vol1
```

You can try running Wyng with the `--debug` option to see what is in /tmp/wyng*/error.log.

**Comment by tasket** [comment]
Can't reproduce.
