### ISSUE TITLE
Feature request: Handle I/O errors more gracefully and continue iterating volumes

### ISSUE THREAD

**Issue by d2x** [tasket/wyng-backup#178]
In the event of an I/O error from a failing disk, the script crashes (v0.8beta2). This could be handled a little better with a try / catch and perhaps throwing a warning that a volume failed to be backed up rather than outright crashing.

```
Volume 'vm-d8-root': Traceback (most recent call last):
  File "/usr/local/bin/wyng", line 4667, in <module>
    monitor_send(storage, aset, selected_vols, monitor_only=False)
  File "/usr/local/bin/wyng", line 3467, in monitor_send
    send_volume(storage, vol, curtime, ses_tags, send_all=datavol in send_alls)
  File "/usr/local/bin/wyng", line 3158, in send_volume
    vf_seek(addr)    ; buf = vf_read(chunksize)
OSError: [Errno 5] Input/output error
None
None
```

Overall, really liking the wyng backup script.

**Comment by tasket** [comment]
Thanks for the report!  FWIW, Wyng does have a concept of trying all then reporting errors at the end; this is done mostly for errors that are Wyng-specific.  However, as you point out, the catching of system errors is sparse and could be expanded so that more volumes can be processed in an error-bound session.
