### ISSUE TITLE
Assertion failure in monitor

### ISSUE THREAD

**Issue by Eric678** [tasket/wyng-backup#218]
wyng monitor --- the archive passes full arch-check fine. There are 2-4 sessions for each volume.
```
Wyng 0.8 beta release 20240827

Preparing snapshots in '/dev/qubes_dom0/'...
Warning: Local '/dev/qubes_dom0/boot' does not exist!
Warning: Local '/dev/qubes_dom0/efi' does not exist!
Warning: Local '/dev/qubes_dom0/vm-sys-usb-private' does not exist!
Warning: Local '/dev/qubes_dom0/wyng-qubes-metadata' does not exist!
Acquiring deltas.
  6222 ch, 7 dis| root
  344 ch, 0 dis | vm-anon-whonix-private
Traceback (most recent call last):
  File "/usr/local/bin/wyng", line 5115, in <module>
    monitor_send(storage, aset, vols or selected_vols, monitor_only=True)
  File "/usr/local/bin/wyng", line 3814, in monitor_send
    updated, svsize, vperms = storage.process_deltas(storage, aset, datavol, monitor_only)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/wyng", line 3184, in update_delta_digest_lvm
    assert t1 == t2
           ^^^^^^^^
```

**Comment by Eric678** [comment]
@tasket I presume this is the result of the above (on next backup after the assert fail):
```
Removed mis-matched snapshot for 'vm-anon-whonix-private'
  Queuing full scan of 'vm-anon-whonix-private'
```
I notice that I have a .tick and .tock LV for each qube, not sure when they appeared, assumed left over from above, noticed a couple of days later.
Guessing that the .tock is a renamed .tick when a vol is queued and a new .tick is forked?
I bit more info on how wyng works for those that don't read python would be useful to decide what to do when there is a failure.

The backup that had the above warning eventually failed 6 qubes later with:
```
Traceback (most recent call last):
  File "/usr/local/bin/wyng", line 5125, in <module>
    sid = monitor_send(storage, aset, vols or selected_vols, monitor_only=False, use_sesid=sid,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/wyng", line 3835, in monitor_send
    send_volume(storage, vol, curtime, ses_tags, send_all=datavol in send_alls)
  File "/usr/local/bin/wyng", line 3598, in send_volume
    raise RuntimeError("tar transport failure code %d" % retcode)
RuntimeError: tar transport failure code 1

```
Given that tar exit 1 is due to a file mod time changing during backup, could this be related to the assert fail in monitor?
Nothing much was running and I was just watching the backup terminal. How to recover?
Thanks

**Comment by t-gh-ctrl** [comment]
FWIW I get the same error message as the OP.

Actions other than 'monitor' work (eg. no "mis-matched snapshot" or other errors).

Qubes OS 4.2.3 / wyng 0.8 beta 20250117

verify OK:

```
$ sudo wyng verify vm-infra-private

Wyng 0.8 beta release 20250117
Encrypted archive 'qubes-ssh://vm-bkp:user@ssh_host:/dstdir'
Last updated 2025-01-21 16:11:23.357782 (+02:00)

Verifying volume 'vm-infra-private' 20250121-161115
[||||||||||||||||||||] 100% : OK  Data bytes: 992544919 / 4001366016
```

send OK:

```
$ sudo wyng send vm-infra-private
Wyng 0.8 beta release 20250117
Encrypted archive 'qubes-ssh://vm-bkp:user@ssh_host:/dstdir'
Last updated 2025-01-21 16:11:23.357782 (+02:00)

Preparing snapshots in '/dev/qubes_dom0/'...
Acquiring deltas.

Sending backup session 20250121-161324:
——————————————————————————————————————————
  no change |  -  | vm-infra-private
——————————————————————————————————————————
1 volumes, 3816——>0 MB in 0.8 seconds.
```

monitor fails:

```
$ sudo wyng monitor vm-infra-private
Wyng 0.8 beta release 20250117
Encrypted archive 'qubes-ssh://vm-bkp:user@ssh_host:/dstdir'
Last updated 2025-01-21 16:11:23.357782 (+02:00)

Preparing snapshots in '/dev/qubes_dom0/'...
Acquiring deltas.

Monitor at 20250121-161334:
——————————————————————————————————————————
Traceback (most recent call last):te
  File "/usr/local/bin/wyng", line 5229, in <module>
    monitor_send(storage, aset, vols or selected_vols, monitor_only=True)
  File "/usr/local/bin/wyng", line 3902, in monitor_send
    updated, svsize, vperms = storage.process_deltas(storage, aset, datavol, monitor_only)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/wyng", line 3250, in update_delta_digest_lvm
    assert t1 == t2
           ^^^^^^^^
AssertionError
```

list of related volumes:

```
$ sudo lvdisplay | grep "LV Path.*vm-infra-private"

  LV Path                /dev/qubes_dom0/vm-infra-private-1737394484-back
  LV Path                /dev/qubes_dom0/vm-infra-private-1737461086-back
  LV Path                /dev/qubes_dom0/vm-infra-private
  LV Path                /dev/qubes_dom0/vm-infra-private-snap
  LV Path                /dev/qubes_dom0/vm-infra-private.tick
```

**Comment by tasket** [comment]
@Eric678 @t-gh-ctrl Fix posted to 08beta branch.
