### ISSUE TITLE
exception when sending volume with --dedup

### ISSUE THREAD

**Issue by taradiddles** [tasket/wyng-backup#95]
Hi @tasket ! It's been a long time, I hope you're doing well...
Again, thanks for your work on wyng, it's really a time saver compared to `qvm-backup`.

So, I've migrated from Qubes OS 4.0 to 4.1 the other day and I'm now encountering an issue when sending volumes with the `--dedup` option. My setup is the same as for 4.0 so except a probably upgraded python in 4.1 I'm wondering what has changed as everything was working perfectly under 4.0.

Setup: luks volume attached to dom0, `cryptsetup luksOpen` done in dom0, destination is internal (dest mountpoint is `/mnt/qubesbkp`, destdir is `wyng`), fs is xfs(noatime).

Steps:

start with a "clean" environement:
```
./wyng delete vm-fedora-minimal-root
ls /mnt/qubesbkp/wyng/wyng.backup/default/ | grep minimal # -> empty
ls /var/lib/wyng.backup/default/ | grep minimal # -> empty
./wyng add vm-fedora-minimal-root # that's one of my fedora templates
Wyng 0.3.0rc2 20210622
Volume vm-fedora-minimal-root added to archive config.
```

This works:

```
./wyng send vm-fedora-minimal-root
Wyng 0.3.0rc2 20210622
Preparing snapshots...
  Pairing snapshot for vm-fedora-minimal-root

Sending backup session 20220211-122032 to /mnt/qubesbkp/wyng
  100%     957.5M  |  vm-fedora-minimal-root 
```

This doesn't:

```
./wyng --dedup send vm-fedora-minimal-root
Wyng 0.3.0rc2 20210622
Preparing snapshots...
  Pairing snapshot for vm-fedora-minimal-root

Sending backup session 20220211-122426 to /mnt/qubesbkp/wyng
  24.2%     118MTraceback (most recent call last):
  File "/usr/local/bin/wyng", line 2981, in <module>
    monitor_send(datavols, selected_vols, monitor_only=False)
  File "/usr/local/bin/wyng", line 1810, in monitor_send
    dnew       = send_volume(datavol, localtime, ses_tags, send_all=datavol in send_alls)
  File "/usr/local/bin/wyng", line 1589, in send_volume
    tarf_addfile(tarinfo=tar_info, fileobj=BytesIO(buf))
  File "/usr/lib64/python3.8/tarfile.py", line 1999, in addfile
    copyfileobj(fileobj, self.fileobj, tarinfo.size, bufsize=bufsize)
  File "/usr/lib64/python3.8/tarfile.py", line 250, in copyfileobj
    dst.write(buf)
  File "/usr/lib64/python3.8/tarfile.py", line 436, in write
    self.__write(s)
  File "/usr/lib64/python3.8/tarfile.py", line 444, in __write
    self.fileobj.write(self.buf[:self.bufsize])
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <function _Stream.__del__ at 0x76ded1fcb940>
Traceback (most recent call last):
  File "/usr/lib64/python3.8/tarfile.py", line 410, in __del__
    self.close()
  File "/usr/lib64/python3.8/tarfile.py", line 460, in close
    self.fileobj.write(self.buf)
BrokenPipeError: [Errno 32] Broken pipe
```
(`--debug` doesn't show anything different)

Notes:
- I'm sending only one volume to illustrate this bug report (no idea if --dedup even has any effect with just one volume) but in practice I'd be sending multiple similar volumes at once, eg. all my fedora templates, all my windows VMs, ...
- I've made a backup of previous wyng backups (with `cp -al`) but they are in `/mnt/qubesbkp/wyng-4.0` so they shouldn't interfere with hardlink/dedup of `/mnt/qubesbkp/wyng`.

Any clue ?

**Comment by taradiddles** [comment]
I found the problem: I had some VMs configured in `/var/lib/wyng.backup/default/archive.ini` that I had manually removed from the wyng archive while testing stuff. `wyng` probably tried to link to some non-existent files (although that's just a guess, the exception message is totally generic).
